spring:
  datasource:
    url: jdbc:mysql://localhost:3306/healthotwechat?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:

#redis数据源
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0

#项目端口和路径
server:
  port: 8080
  context-path: /

#mapper路径
mapper:
  mappers: com.xust.healthotwechat.entity


#微信配置
wechat:
  appid:  wx0061c96846bcbf03
  secret: f4cc9ee4b4f35011a423bd9a7124ba9e
  token:  evildoer_xiaoxu;

  url:
    accesstokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
    menuCreateUrl:  https://api.weixin.qq.com/cgi-bin/menu/create?access_token=ACCESS_TOKEN







