spring:
  datasource:
    url: jdbc:mysql://localhost:3306/healthotwechat?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  thymeleaf:
    prefix: classpath:/templates/
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0


server:
  port: 8080
  context-path: /




mapper:
  mappers: com.xust.healthotwechat.entity
logging:
  level: debug








